config/routes.rb
Rails.application.routes.draw do
  get 'attach/:id', to: 'task_user#attach', as: 'attach'
  get 'dettach/:id', to: 'task_user#dettach', as: 'dettach'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :task, only: [:index, :show]
  root 'task#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include ActionView::Helpers::DateHelper
end

app/models/task.rb
class Task < ApplicationRecord
    has_and_belongs_to_many :users
    @@now = Time.now
    def diff_for_hummans
        distance_of_time_in_words(@@now, created_at) 
    end

    def check_done_task(current_task, user)
        user = User.find(user.id)
        user.tasks.exists? current_task.id
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def done_task user
    user = User.find user.id
    completed = user.tasks.count
    task = Task.all.count
    "Estimado usuario #{user.email}, usted a completado #{completed}/#{task} tareas"   
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @first_user_taks = @task.users.limit(5)
  end
end

app/controllers/task_user_controller.rb
class TaskUserController < ApplicationController
  def attach
    @task = Task.find(params[:id])
    @is_done = current_user.tasks << @task unless current_user.tasks.exists? @task.id
    if @is_done
      redirect_to root_path, notice: "Estimado #{current_user.email}, la tarea #{@task.title}, a sido agregada satisfactoriamente."
    else
      redirect_to root_path, alert: 'La tarea no pudo ser agregada a tu lista'
    end
  end

  def dettach
    @task = Task.find(params[:id])
    @is_remove = current_user.tasks.delete @task if current_user.tasks.exists? @task.id
    if @is_remove
      redirect_to root_path, notice: "Estimado #{current_user.email}, la tarea #{@task.title}, a sido retirada satisfactoriamente."
    else
      redirect_to root_path, alert: 'La tarea no pudo ser removida de tu lista, ya que no la haz realizado'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/task_user_helper.rb
module TaskUserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioLatamPrueba2Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>  
      <header>
        <div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container d-flex justify-content-between">
            <a href="<%= root_path %>" class="navbar-brand d-flex align-items-center">
              <strong>Bucket List del 18°</strong>
            </a>
            <small class="text-muted"> <%= current_user.done_task current_user if user_signed_in? %> </small>
            <a class="btn btn-sm btn-info" href="<%= destroy_user_session_path %>" data-method="DELETE">Logout</a>
          </div>
        </div>
      </header>
  
      <main role="main">  
        <div class="album py-5 bg-light">
          <div class="container">
            <% if notice != nil%>
              <div class="alert alert-secondary" role="alert">
                <%= notice %>
                <%= alert %>
              </div>
            <% end %>

            <%= yield %>
          </div>
        </div>
      </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/task/index.html.erb
<div class="row">
    <% @tasks.each do |task| %>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="<%= task.img %>" alt="<%= task.title %>" height="225" width="100">
            <div class="card-body">
                <p class="card-text">
                    <%= task.title %>
                </p>
                <div class="d-flex justify-content-between align-items-center"> 
                    <%= link_to  "Ver", task_path(task), class:"btn btn-sm btn-outline-success" %>
                    <% if task.check_done_task(task, current_user) %> 
                        <%= link_to  "Eliminar Tarea", dettach_path(task), class:"btn btn-sm btn-outline-danger" %>
                    <% else %>
                        <%= link_to  "Realizar Tarea", attach_path(task), class:"btn btn-sm btn-outline-info" %>
                    <% end %>
                    <small class="text-muted"><%= task.diff_for_hummans %></small>
                </div>
            </div>
            </div>
        </div>
    <% end %>
</div>

app/views/task/show.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="card mb-4 shadow-sm">
        <img class="card-img-top" src="<%= @task.img %>" alt="<%= @task.title %>" height="225" width="100">
        <div class="card-body">
            <p class="card-text">
                <%= @task.title %>
            </p>
            <div class="d-flex justify-content-between align-items-center"> 
                <small class="text-muted"><%= @task.diff_for_hummans %></small>
            </div>
        </div>
        </div>
    </div>

    <div class="col-md-6">
        <% if @first_user_taks == nil %>
            <div class="alert alert-primary" role="alert">
                De momento ningun usuario a completado esta tarea.
            </div>
        <% else %>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col text-right">Usuario</th>
                    </tr>
                </thead>
                <tbody>
                    <% @first_user_taks.each do |user|%>
                        <tr>
                            <th scope="row"><%= user.id %></th>
                            <td class="text-right"> <%= user.email %> </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div> 

</div>